name: telegram_logger
description: "Dart package for logging to Telegram"
version: 0.0.6
#homepage:

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter

  #web
  http: ^1.1.0
  dio: ^5.6.0
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  #utils
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.9
  retrofit_generator: ^8.2.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
#  assets:
#    - .env
