name: telegram_logger
description: "Dart package for logging to Telegram"
version: 0.0.5
#homepage:

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #web
  http: '>=0.13.6'
  dio: '>=5.6.0'
  retrofit: '>=4.2.0'
  json_annotation: '>=4.8.1'
  json_serializable: '>=6.6.2'

  #utils
  logger: '>=2.4.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=2.0.3'

  build_runner: '>=2.3.3'
  retrofit_generator: '>=8.2.0'



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
#  assets:
#    - .env
