name: telegram_logger
description: "Dart package for logging to Telegram"
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #web
  http: ^1.2.2
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  #utils
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: any
  retrofit_generator: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
#  assets:
#    - .env
